resources:
- backend/deploy.yml
- backend/service.yml
- backend/hpa.yml
- frontend/deploy.yml
- frontend/service.yml
- ingress.yml
images:
- name: 654654554686.dkr.ecr.us-east-1.amazonaws.com/devops-na-nuvem-week/production/backend
  newName: 654654554686.dkr.ecr.us-east-1.amazonaws.com/devops-na-nuvem-week/production/backend
  newTag: ad2d5012a5013fdf5829f7005f5a3acc49f8dce1
- name: 654654554686.dkr.ecr.us-east-1.amazonaws.com/devops-na-nuvem-week/production/frontend
  newName: 654654554686.dkr.ecr.us-east-1.amazonaws.com/devops-na-nuvem-week/production/frontend
  newTag: b8e3245d1fc2bbbf0cbbe2b51cba91fe15fae873
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
